name: CI

on:
  push:
    branches: [v3]
  pull_request:
    branches: [v3]

jobs:
  Job:
    name: Node.js
    uses: node-modules/github-actions/.github/workflows/node-test-mysql.yml@master
    with:
      os: 'ubuntu-latest'
      version: '20, 22'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
